services:

  main-api:
    image: main-api
    container_name: main-api
    volumes:
      - ./static:/app/static
    ports:
      - 8001:8001
    command: python main.py

  video-avatar-microservice:
    image: video-avatar-microservice
    container_name: video-avatar-microservice
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./src/external/sadtalker/checkpoints:/home/video-avatar-microservice/src/external/sadtalker/checkpoints
      - ./src/external/sadtalker/gfpgan/weights:/home/video-avatar-microservice/src/external/sadtalker/gfpgan/weights
      - ./src/external/sadtalker/results:/home/video-avatar-microservice/src/external/sadtalker/results
      - ./static:/home/video-avatar-microservice/static
    ports:
      - 8002:8002
    command: bash